// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDGBr8KCe3hXnqc8QSa-3D7LUpys8KHww',
    appId: '1:477331463576:web:a147c02635f15d97389fed',
    messagingSenderId: '477331463576',
    projectId: 'chat-fa542',
    authDomain: 'chat-fa542.firebaseapp.com',
    storageBucket: 'chat-fa542.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6icmdPUZa2SW6yorJd1PTkNHwZHE04fc',
    appId: '1:477331463576:android:4c55a17fe47808e0389fed',
    messagingSenderId: '477331463576',
    projectId: 'chat-fa542',
    storageBucket: 'chat-fa542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIPYvQxiVdQaxHRRwu5rwB5ixae5R8s0',
    appId: '1:477331463576:ios:5dd8771ffc98a0af389fed',
    messagingSenderId: '477331463576',
    projectId: 'chat-fa542',
    storageBucket: 'chat-fa542.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhIPYvQxiVdQaxHRRwu5rwB5ixae5R8s0',
    appId: '1:477331463576:ios:306a307b25408304389fed',
    messagingSenderId: '477331463576',
    projectId: 'chat-fa542',
    storageBucket: 'chat-fa542.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
